services:
    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis-data:/data
        environment:
            REDIS_ARGS: --save 300 1 60 10
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5

    backend:
        image: ghcr.io/vencord/vencloud:latest
        restart: always
        environment:
            HOST: 0.0.0.0
            PORT: 8080
            REDIS_URI: redis:6379
            ROOT_REDIRECT: ${ROOT_REDIRECT:-https://vencord.dev}
            DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
            DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
            DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}
            PEPPER_SETTINGS: ${PEPPER_SETTINGS}
            PEPPER_SECRETS: ${PEPPER_SECRETS}
            SIZE_LIMIT: ${SIZE_LIMIT:-1048576}
            ALLOWED_USERS: ${ALLOWED_USERS:-}
            PROXY_HEADER: ${PROXY_HEADER:-X-Forwarded-For}
            PROMETHEUS: ${PROMETHEUS:-false}
        depends_on:
            redis:
                condition: service_healthy
        ports:
            - "8080:8080"

volumes:
    redis-data:
